detect start.sh

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
-ls -l
-
-exit 0
+if [ -e "start.sh" ]
+then
+	echo "start.sh found"
+	exit 0
+else
+	echo "start.sh not found"
+	exit 1
+fi
